-   name: NextRes
    href: http://nextres.mit.edu/
-   name: Room Reservations
    href: /reservations
-   name: Community Handbook
    href: /static/NextHouseCommunityHandbookFall2017.pdf
-   name: Laundry
    href: http://www.laundryview.com/laundry_room.php?lr=1364812
-   name: Submit a Work Order
    href: /static/workorder.pdf
-   name: Submit an RFP
    href: https://docs.google.com/document/d/1HF1ftAAU2IlQppoH_yfKj35y9t2Lz1H1njt76GW5ndE/edit
-   name: Printing
    href: /printing
-   name: Dining Menu
    href: http://mit.cafebonappetit.com/cafe/next/
-   name: Budget
    href: https://docs.google.com/spreadsheets/d/1fF2obayeV1hMSmPi6ywHpnd4uTEfojEb7n4V_iRn-po/edit
-   name: Student Group Petition
    href: https://docs.google.com/forms/d/e/1FAIpQLSfrEHzK6QHHLJjRjJ8kmUtkuaxuqB7whhbi17Pi-hibU7dIGQ/viewform
